SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[DENEME] AS
BEGIN TRY
BEGIN TRANSACTION


INSERT INTO TestTable (sKOD,SAD) VALUES ('0001','Naz');

COMMIT
END TRY
BEGIN CATCH

ROLLBACK TRANSACTION

END CATCH
GO